### ISSUE TITLE
Bookworm raspi-config  keyboard selection bug

### ISSUE THREAD

**Issue by PitHerm** [raspberrypi/bookworm-feedback#74] opened 2023-10-15 08:35 UTC
bookworm (tested only on x64)
all avaiable updates done

using remote putty connection
sudo raspi-config

5 Localisation Options 
L3 Keyboard > appears Reloading keymap > then raspi-config back at main menu
no setting possible

on direct console at pi it works.

**Comment by XECDesign** [comment] 2023-10-16 13:04
I'm guessing that was meant to be arm64, now x64?

Desktop or lite image?

**Comment by PitHerm** [comment] 2023-10-16 13:35
Bookworm 64bit full image installed on Pi4 B using Pi-Imager

**Comment by XECDesign** [comment] 2023-10-16 13:45
Thanks. It worked for me when I tried, but I was running 32bit desktop image and sshing in without using putty. I'll try to reproduce the issue with your setup when I get a chance.

**Comment by PitHerm** [comment] 2023-10-16 15:01
I just tested Bookworm Desktop 32 and 64 bit ; Bookworm OS FULL 32 and 64 bit
using Pi Imager with applying settings
Enable SSH
user = pi
PW = raspberry
enable Wifi > setting ssid and password (even triid leaving the country setting and keyboard setting to GB vs setting them to DE)

wrote every image

tested putty connection > sudo raspi-config > set keyboard >FAILED
installed xrdp > tested remote Desktop from Windows > login > xterm >sudo raspi-config > set keyboard >FAILED

then: sudo apt update > sudo apt upgrade 
tested putty connection > sudo raspi-config > set keyboard >FAILED
 tested remote Desktop from Windows > login > xterm >sudo raspi-config > set keyboard >FAILED

![1](https://github.com/raspberrypi/bookworm-feedback/assets/93200753/71ed7f03-f50d-4075-a600-2935a54ee625)

![2](https://github.com/raspberrypi/bookworm-feedback/assets/93200753/d089bf86-80b2-4213-afa4-62a0f29b6eb1)

**Comment by qrp73** [comment] 2023-10-17 04:37
Keboard layout config in raspi-config is broken by design. It doesn't allows you to configure layout list and define hot key to change layout. It only allows to select single layout, so you will be unable to use ASCII keys if you select non engilsh layout. 

The only way to configure keyboard properly is to edit config files directly. 
Here is example with 3 layouts: US, RU, UA and Alt+Shift key for layout switch:

1) for console: sudo nano /etc/default/keyboard
```
XKBMODEL="pc105"
XKBLAYOUT="us,ru,ua"
XKBVARIANT=""
XKBOPTIONS="grp:alt_shift_toggle"
```

2) for Wayland: nano ~/.config/wayfire.ini
```
[input]
xkb_options = grp:alt_shift_toggle
xkb_model = pc105
xkb_layout = us,ru,ua
xkb_variant =
```

3) For login screen: sudo nano /usr/share/greeter.ini
```
[input]
xkb_options = grp:alt_shift_toggle
xkb_model = pc105
xkb_layout = us,ru,ua
xkb_variant =
```

**Comment by lurch** [comment] 2023-10-17 09:49
> It doesn't allows you to configure layout list and define hot key to change layout.

Even if that is the case, it seems to be unrelated to the issue being reported here? :thinking:

**Comment by qrp73** [comment] 2023-10-17 16:19
Since it talking about keyboard layout in raspi-config, I wrote it here just to note that this functionality of raspi-config is invalid and needs to be rewritten, also added example on how raspi-config should hanlde keyboard settings, it will be helpful for developers who will working on that feature.

**Comment by lurch** [comment] 2023-10-17 21:54
> I wrote it here just to note that this functionality of raspi-config is invalid and needs to be rewritten, also added example on how raspi-config should hanlde keyboard settings,

That should probably be logged as a separate issue, rather than added to this one.

**Comment by qrp73** [comment] 2023-10-18 04:41
There is no sense to fix it separately, because it will be automatically fixed if keboard layout setting in raspi-config will be rewritten in proper way.

**Comment by lurch** [comment] 2024-07-18 16:23
@XECDesign I was digging in to this today, and finally managed to figure out how to reproduce it...
`raspi-config` does "Localisation Options" -> "Keyboard" by running `dpkg-reconfigure keyboard-configuration`.

If I'm connected to my Pi over SSH and I have a USB keyboard attached, then `sudo dpkg-reconfigure keyboard-configuration` displays the expected interactive keyboard-selection program. But if I **don't** have a USB keyboard attached to the Pi, then `sudo dpkg-reconfigure keyboard-configuration` just silently exits without doing anything. And this explains why it always worked for @XECDesign (because they always had a USB keyboard attached) but why it didn't work for @PitHerm (because they never had a USB keyboard attached) :joy: 

@XECDesign / @spl237 Is having no keyboard attached something that we could "detect" inside `raspi-config`, and then display a suitable warning message to the user if they try to run "Localisation Options" -> "Keyboard" ?

**Comment by spl237** [comment] 2024-07-18 16:26
> @XECDesign / @spl237 Is having no keyboard attached something that we could "detect" inside `raspi-config`, and then display a suitable warning message to the user if they try to run "Localisation Options" -> "Keyboard" ?

Detecting the lack of a keyboard is harder than you think! The problem is wireless dongles, which invariably seem to identify themselves as keyboards even when they aren't associated with one. Don't know if that would be a problem here though.

**Comment by lurch** [comment] 2024-07-18 16:31
Alternatively, could we force `dpkg-reconfigure keyboard-configuration` to _always_ run, even if it thinks that there isn't a keyboard connected?

**Comment by XECDesign** [comment] 2024-07-22 09:14
I had to add an [ugly workaround](https://github.com/RPi-Distro/pi-gen/commit/165e9602376b1ee25d8599389e5ae5643dd9754c) for a somewhat related problem in pi-gen. The scripts under the hood of keyboard-configuration are a bit of a mess and I wouldn't want to start patching them without understanding why the behave the way they do.

If a user tries to configure a keyboard that does not exist and debian's scripts don't take that situation into account, I don't think that's a problem with Raspberry Pi OS. I don't think we're doing anything wrong or unusual.

**Comment by lurch** [comment] 2024-07-23 13:35
> I don't think we're doing anything wrong or unusual.

Fair enough, I'll close this issue. @nathan-contino perhaps https://www.raspberrypi.com/documentation/computers/configuration.html#localisation-options needs to be updated to mention that trying to configure a keyboard won't do anything if there's not actually a USB keyboard attached?

**Closed as not planned by lurch** 2024-07-23 13:35 UTC

**Comment by jumperger** [comment] 2024-08-14 17:50
I'm still having this raspi-config keyboard problem even with a wired usb-Keyboard connected at boot

**Comment by XECDesign** [comment] 2024-08-14 18:37
Are you running raspi-config over ssh or not?
