### ISSUE TITLE
audacity stopped to work after latest apt upgrade

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#296] opened 2024-09-19 14:54 UTC
Steps to reproduce:

1)  ```sudo apt update && sudo apt upgrade```
2)  Start audacity

Expected result: audacity is started and works (as it worked before apt upgrade)

Actual result: audacity is in dead loop at app splash

app log:
```
$ audacity

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

dmesg log:
```
[   49.117626] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[   54.237582] usb 1-1.4.4: 2:0: usb_set_interface failed (-110)
[   59.357563] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[   64.477280] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[   64.477308] usb 1-1.4.4: clock source 9 is not valid, cannot use
[   69.597214] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[   74.717378] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[   79.837637] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[   84.957947] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[   90.077532] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[   90.077548] usb 1-1.4.4: clock source 9 is not valid, cannot use
[   95.197608] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  100.322037] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  105.438101] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  110.562443] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  115.677647] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  115.677663] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  120.797711] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  125.917647] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  131.294145] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  136.413870] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  141.533949] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  141.533966] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  146.656940] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  151.774573] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  156.898721] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  162.018948] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  167.134983] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  167.135001] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  172.254710] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  177.374811] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  182.495280] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  187.615267] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  192.734947] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  192.734963] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  197.859117] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  202.975187] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  208.095608] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  213.219666] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  218.335266] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  218.335281] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  223.455335] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  228.575262] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  233.696409] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  238.815681] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  243.935664] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  243.935680] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  249.055378] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  254.175490] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  259.295864] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  264.415958] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  269.535883] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  269.535911] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  274.656154] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  279.776168] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  284.896790] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  290.016932] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  295.136687] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  295.136706] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  300.257016] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  305.376885] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  310.497511] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  315.617890] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  320.737439] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  320.737455] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  325.857515] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  330.977648] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
[  336.098417] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  341.218366] usb 1-1.4.4: 1:0: usb_set_interface failed (-110)
[  346.338347] usb 1-1.4.4: uac_clock_source_is_valid(): cannot get clock validity for id 9
[  346.338393] usb 1-1.4.4: clock source 9 is not valid, cannot use
[  351.458084] usb 1-1.4.4: 1:3: cannot get freq (v2/v3): err -110
[  356.578131] usb 1-1.4.4: 1:3: cannot set freq 48000 (v2/v3): err -110
```

Please fix it

**Comment by popcornmix** [comment] 2024-09-19 16:01
I've just tried `sudo apt install audacity` on a fresh 64-bit RPiOS bookworm image and it launched okay.
Also tried on an older image (after `apt full-upgrade`) and it launched there too.

Do you have a USB audio device connected? Does it start without that connected?

**Comment by popcornmix** [comment] 2024-09-19 16:02
Note:
```
$ audacity

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:1862): Gdk-CRITICAL **: 17:50:25.896: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```
appear on a working launch, so are likely unrelated to your issue.

**Comment by qrp73** [comment] 2024-09-19 16:33
I think it is freezes in dead loop due to error with sound card. Because when I disconnect the sound card from USB, it starts ok.

It appears that if I start youtube in firefox first (after reboot) the error don't happens.

**Comment by popcornmix** [comment] 2024-09-19 16:37
Any complaints about USB in dmesg?

It sounds more like a kernel issue than an audacity one.

**Comment by qrp73** [comment] 2024-09-19 16:41
yes, it seems like kernel issue with usb.

just tried to reboot and now it works ok. I suspect it may be related to specific video which was played in youtube, may be due to some specific sample rate.

**Comment by qrp73** [comment] 2024-09-27 21:13
It looks that this is the same issue as this one: https://github.com/raspberrypi/bookworm-feedback/issues/288

**Comment by lurch** [comment] 2024-10-02 12:42
Closing as duplicate of #288

**Closed as not planned by lurch** 2024-10-02 12:42 UTC
