### ISSUE TITLE
Bookworm32 install images bug concerning vnc server

### ISSUE THREAD

**Issue by PitHerm** [raspberrypi/bookworm-feedback#155] opened 2023-11-28 07:58 UTC
Test equipment:
PC + Win10 + vnc viewer 7.8.0 + putty
Pi5(8GB) ; Pi4(4GB)
Raspberry Pi OS FULL (32Bit) ; Raspberry Pi OS FULL (64Bit) (I suppose the same problem happens with the other 32bit images)
Pi Imager
Micro SD-Card

Test 1 (done for Pi5 and Pi4):
write Raspberry Pi OS FULL (64Bit) to the Micro SD using Pi imager with wlan and SSH enabled.
Establich a SSH connection to the Pi and log in.
run sudo raspi-config >> Advanced Options >> Wayland >>  W1 X11
leave raspi-config and wait for reboot . then Establich a SSH connection to the Pi and log in again
run sudo raspi-config >> Interface Options >>  VNC >> enable
leave raspi-config > logout
launch vnc viewer on the PC and try to establish a connection >> It Works !
after doing all updates vnc is still working.

Test 2 (done for Pi5 and Pi4):
write Raspberry Pi OS FULL (32Bit) to the Micro SD using Pi imager with wlan and SSH enabled.
Establich a SSH connection to the Pi and log in.
run sudo raspi-config >> Advanced Options >> Wayland >>  W1 X11
leave raspi-config and wait for reboot . then Establich a SSH connection to the Pi and log in again
run sudo raspi-config >> Interface Options >>  VNC >> enable
leave raspi-config > logout
launch vnc viewer on the PC and try to establish a connection >> FAIL , can't establish a connection !!!
doing all updates  >> same result.

**Comment by lurch** [comment] 2023-11-29 10:57
Duplicate of #41

**Closed as completed by lurch** 2023-11-29 10:57 UTC
