### ISSUE TITLE
Raspberry Pi GPIO and Raspberry Pi Sense HAT from Scratch3 doesn`t work on Raspberry Pi 5 32 bit and 4kb size pages

### ISSUE THREAD

**Issue by SivaVasudevan0204** [raspberrypi/bookworm-feedback#152] opened 2023-11-24 11:14 UTC
Hello, im trying to use Raspberry Pi GPIO and Raspberry Pi Sense HAT from Scratch3 in Raspberry Pi 5. but its didnt response. Btw Im using 32 bit and 4kb size pages. Can anyone help me out?

**Comment by aallan** [comment] 2023-11-24 14:00
Duplicate of #91

**Comment by SivaVasudevan0204** [comment] 2023-11-27 06:06
i think this is not related to #91. because i can use other features of scratch3 in RPi5...seems the extension Raspberry Pi GPIO and Raspberry Pi Sense HAT is only not working for me in RPi5. btw im using 32 bit and 4kb size pages. Can help me to solve this
![20231127_06h03m12s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/151894226/ff03970c-1279-4707-a253-728710b6558a)

**Comment by SivaVasudevan0204** [comment] 2023-11-27 06:14
![20231127_06h08m41s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/151894226/c5c90f8a-8501-49e8-99c2-4a1e3e7f537a)
im trying to display the A text..but the led just on like rainbow only..didnt even change since i plugin the sense Hat in my RPi5

**Comment by lurch** [comment] 2023-11-27 10:30
Duplicate of #148

**Closed as completed by lurch** 2023-11-27 10:30 UTC
