### ISSUE TITLE
OS root/boot archives are not updated

### ISSUE THREAD

**Issue by mdevaev** [raspberrypi/bookworm-feedback#145] opened 2023-11-15 02:27 UTC
Here:
* https://downloads.raspberrypi.com/raspios_lite_arm64/
* https://downloads.raspberrypi.com/raspios_lite_armhf/
* https://downloads.raspberrypi.com/raspios_full_arm64/
* https://downloads.raspberrypi.com/raspios_full_armhf/

Files `boot.tar.xz` are `root.tar.xz` are not updated and belongs to bullseye. `os.json` is not updated too and points ro previous image release.

**Comment by lurch** [comment] 2023-11-15 09:44
Those files were only used by [NOOBS](https://github.com/raspberrypi/noobs), and NOOBS got deprecated a _long_ time ago, so those files are no longer being updated.

**Comment by lurch** [comment] 2023-11-15 09:46
Duplicate of #78

**Closed as not planned by lurch** 2023-11-15 09:46 UTC

**Comment by mdevaev** [comment] 2023-11-15 12:37
@lurch is it possible to provide complete tar archive for whole rootfs besides img files? This would be handy for creating docker images. To convert an img to a root archive, we need to perform losetup and many other actions.
