### ISSUE TITLE
pcmanfm - File Manager - Can't right-click Paste into the home directory or an immediate subdirectory when in ListView mode

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#303] opened 2024-10-10 06:52 UTC
The "Paste" option is unavailable after single click on "Copy" menu, requiring the user to click "Copy" menu at least twice in order to use "Paste" menu.

### Steps to Reproduce:

1) Open File Manager (pcmanfm).
2) Right-click on a file and select "Copy" from the context menu.
3) Double-click on another folder to change the current directory.
4) Right-click in the new folder and attempt to select "Paste" from the context menu.

**Expected Result:** The "Paste" option should be available and should paste the previously copied file into the new folder.

**Actual Result:** The "Paste" option is unavailable. The user is forced to select "Copy" at least twice before being able to paste the file.

**Impact:** This issue has been present for a long time and is highly disruptive to workflow, requiring unnecessary repetition of actions to complete a basic task. It greatly affects usability and efficiency in file management.

**Recommendation:** Fix the issue so that the "Paste" become accessible after single select "Copy" menu, without requiring the user to re-select "Copy" again.

**Comment by lurch** [comment] 2024-10-10 12:34
I'm not able to reproduce this - it all works perfectly fine for me. Can you please provide more details about which OS image / desktop environment / Raspberry Pi / etc. you're using?

**Comment by qrp73** [comment] 2024-10-10 13:44
Raspberry Pi 4B rev 1.5
```
$ uname -a && cat /etc/rpi-issue && vcgencmd version
Linux raspi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
Raspberry Pi reference 2023-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 40f37458ae7cadea1aec913ae10b5e7008ebce0a, stage4
Aug 30 2024 19:17:39 
Copyright (c) 2012 Broadcom
version 2808975b80149bbfe86844655fe45c7de66fc078 (clean) (release) (start)
```

As I remember this issue was present just out of the box after all Raspberry Pi OS installation.
Currently I also installed clipman, but this issue was present before installation.

This is very strange that you cannot reproduce it. Do you use context menu by right click mouse?


Maybe it is related to pcmanfm settings? I'm using Detailed List View, and disabled Layout->Display simplified user interface and menus

**Comment by lurch** [comment] 2024-10-10 14:22
> I'm using Detailed List View

Ah! That seems to be the problem. If I click on the "View as detailed list" button on the toolbar, then the right-click "Paste" menu indeed appears to stop working. Although the Edit->Paste menu _does_ still seem to work, so I guess that's a workaround for now whilst we investigate this problem...

**Comment by popcornmix** [comment] 2024-10-10 14:24
Just tried and a copied a file and pasted it into a new directory just fine. This was using right-click menu options.
This was on a Pi5 with labwc enabled.

**Comment by lurch** [comment] 2024-10-10 15:04
Ah-ha! After a bit more head-scratching, myself and @popcornmix have managed to figure out why it works sometimes but not others. :bulb: 

If you've switched pcmanfm into List-view, **and** you're trying to right-click-Paste into your home directory or an immediate subdirectory of your home directory, then the Paste silently fails. But if you try and Paste into a sub-sub-directory (which is what @popcornmix was trying), then the Paste succeeds! How bizarre.

Detailed reproduction steps:
1. Launch pcmanfm (File Manager) and create a new directory in your home folder e.g. `SubDir`
2. Navigate into `SubDir` and create another directory inside there e.g. `SubSubDir` (i.e. so the full path is something like `/home/pi/SubDir/SubSubDir`)
3. Navigate back to your home directory
4. Create two new empty files e.g. `File1` and `File2`
5. Make sure that pcmanfm is in "Icon View" mode
6. Right-click on File1, select Copy
7. Navigate to SubDir
8. Right-click and select Paste - this works and creates File1
9. Navigate back to your home directory
10. Right-click on File2, select Copy
11. Navigate to SubSubDir
12. Right-click and select Paste - this works and creates File2
13. Now delete SubDir/File1 and SubDir/SubSubDir/File2
14. Navigate back to your home directory
15. Switch pcmanfm to "List View" mode
16. Right-click on File1, select Copy
17. Navigate to SubDir
18. Right-click and select Paste - **this silently fails**
19. Navigate back to your home directory
20. Right-click on File2, select Copy
21. Navigate to SubSubDir
22. Right-click and select Paste - this works and creates File2

**Comment by qrp73** [comment] 2024-10-10 21:36
it doesn't depends on sub folder structure at all. 

The Paste operation just don't works if you do Copy operation once. 
If you do Copy operation twice for the same file, the Paste operation works.

You can reproduce it in the same folder: just right-click on the file and select Copy, then right-click on an empty space and verify that Paste is disabled. Then copy the same file a second time, and you will see that Paste is enabled.

The same issue happens if you use Cut instead of Copy.

It is very annoying when you copy a file, then change the current folder to find another location, and when you right-click to paste, you realize that the paste operation is disabled. You then have to find the original file again to copy it a second time.

Just tried to reproduce it with Icon View, and the issue is still present.

Interestingly, if you copy a file once, then restart pcmanfm and copy the same file a second time, the Paste option becomes available. This means the state is somehow remembered between pcmanfm sessions.

Also, there is need to restart pcmanfm after setting changes.

**Comment by qrp73** [comment] 2024-10-19 14:48
Tested on old Bullseye image, it don't have such issue. So it appears in Raspi OS Bookworm.

**Comment by qrp73** [comment] 2024-11-04 11:28
Tested it on a clean raspios install. And found additional details on how to reproduce it. 

In order to reproduce this issue, you need to install clipman: ```sudo apt install clipman``` and add it to wayfire or labwc config.

For wayfire ```nano ~/.config/wayfire.ini```:
```
[autostart]
clipman-restore = clipman restore
clipman-store = wl-paste -t text --watch clipman store
```

For labwc ```mkdir -p ~/.config/labwc && nano ~/.config/labwc/autostart```:
```
/usr/bin/wl-paste -t text --watch clipman store &
```

After that reboot the system and you will be able to reproduce the issue with non working Paste operation in pcmanfm for the single copy operation.

**Comment by qrp73** [comment] 2024-12-08 23:20
This the most annoying issue of Raspberry Pi OS. You catch it every time when copy/paste files. Any chance to fix it?

Without clipman you need to keep process open between text copy/paste. 
With clipman text copy/paste works ok, but you need to copy files twice, otherwise paste will not be available.

**Comment by lurch** [comment] 2024-12-08 23:27
> This the most annoying issue of Raspberry Pi OS. You catch it every time when copy/paste files. Any chance to fix it?

> In order to reproduce this issue, you need to install clipman

`clipman` isn't installed by default in Raspberry Pi OS (and we don't mention it anywhere in our [official documentation](https://www.raspberrypi.com/documentation/) ), and this is why fixing this "most annoying issue" isn't very high on our list of priorities.

**Comment by qrp73** [comment] 2024-12-09 05:25
The issue is not with Clipman, but with **pcmanfm** in Raspberry Pi OS Bookworm, the **pcmanfm fails to copy file** at first attempt. The Clipman just makes it visible.

Is there an alternative method that allows copy/paste functionality without needing to keep both applications open until the operation is complete?

By default, Raspberry Pi OS Bookworm loses copied text when you close the window, which is very inconvenient. If you close an unneeded window, the copied data is lost, and you can no longer paste it. This behavior differs from Raspberry Pi OS Bullseye, where the copied text would persist.

Using Clipman can help preserve clipboard data, but it leads to bugs with copy/paste operations in pcmanfm within Raspberry Pi OS. These issues in Raspberry Pi OS leaving users with limited options and unresolved usability problems, because you're limited with just two option - use clipman or not use, but both option have bugs and any choose leads to very annoying usability issues. Please fix it.

Copy/paste is very important part of modern OS and it's sad to see broken copy/paste behavior in Raspberry Pi OS.

When you are editing text or code for an extended period and then copy it to paste into another window, but close the window from which you copied the text, all your work is lost without the possibility of recovery. This is the default behavior of Raspberry Pi OS Bookworm.

Using Clipman resolves this serious issue - no need to keep all windows open until complete copy/paste operation, you can copy text, close window and paste it in a new window. But it introduces another problem with pcmanfm when copying files - you always have to copy the file twice. If you navigate to another folder in the process, you must return to the original folder and copy the file again because the first file copy operation is always ignored. This is extremely inconvenient.

**Comment by lurch** [comment] 2024-12-09 11:40
> By default, Raspberry Pi OS Bookworm loses copied text when you close the window, which is very inconvenient. If you close an unneeded window, the copied data is lost, and you can no longer paste it. This behavior differs from Raspberry Pi OS Bullseye, where the copied text would persist.

I believe that this is simply a feature of how Wayland works, rather than a bug in Raspberry Pi OS Bookworm.
Personally, I find that whenever I'm copy'n'pasting text between two applications, I always have both applications still running anyway, i.e. I always do "copy, switch to other application, paste", I never do "copy, close original application, switch to other application, paste".

**Comment by spl237** [comment] 2024-12-09 11:53
Wayland does not support copying between two applications or windows unless they are both still running - this is a consequence of the security design of Wayland and nothing to do with anything we have done.

We don't support detailed list view any more, which is why it is disabled by default. Any bugs which only show up in that view are not going to be fixed by us.

**Comment by qrp73** [comment] 2024-12-10 04:44
> I find that whenever I'm copy'n'pasting text between two applications, I always have both applications still running anyway,

this approach doesn't work if you're trying to copy something from a window that automatically closes on losing focus. This often happens in browsers on certain web pages. For instance, if you try to copy a shipment tracking number from a popup window, the window might close as soon as you move the mouse cursor away or switch to another application, causing the copied text to be lost.

Additionally, keeping many unnecessary windows open can be very frustrating, especially if you opened a window solely to copy some text and no longer need it. Having to keep that window open until you paste the text in another application can be annoying, as it requires you to return to the window just to close it after completing the paste operation.

These issues are effectively resolved with clipman. It saves the copied text in its process, allowing you to close the source window, switch back to your document, paste the text, and continue working without the need to return to the now-unnecessary window just to close it.

> Wayland does not support copying between two applications or windows unless they are both still running - this is a consequence of the security design of Wayland and nothing to do with anything we have done.

This is ok, since Linux clipboard model relies on the source application to retain clipboard content. When the source application is closed, the clipboard data is typically lost. This is where tools like clipman come into play, as they store clipboard content independently, ensuring it remains available even after the source application is closed. In this case, clipman functions as expected, enabling successful copy-paste operations from a window that is closed before the paste action.

However, there are issues specific to pcmanfm. It appears to require a double copy operation for unknown reason. Additionally, there is another annoying issue in Raspberry Pi OS pcmanfm - it often causes open the rename dialog unexpectedly. It usually happens when you double click on the folder to open it.

> We don't support detailed list view any more, which is why it is disabled by default. Any bugs which only show up in that view are not going to be fixed by us.

this is sad, because this is the only useful view mode for file list, it allows to see file name and its size and other properties.

But the bug in pcmanfm with unable to copy file on first attempt exists for ANY view mode. 
You can easy reproduce the issue with icon view.

## Steps to reproduce:
1) Setup ANY view mode in pcmanfm preferences

2) Install and configure clipman:
```
sudo apt install clipman
```
For Wayfire: ```nano ~/.config/wayfire.ini```
```
[autostart]
clipman-restore = clipman restore
clipman-store = wl-paste -t text --watch clipman store
```
For labwc: ```nano ~/.config/autostart```
```
/usr/bin/clipman restore &
/usr/bin/wl-paste -t text --watch clipman store &
```

3) Open pcmanfm

4) Right click on some file for the first time and select "Copy" operation

5) Right click again (on empty space)

**Expected result:** "Paste" menu is active

**Actual result:** "Paste" menu is disabled, it requires to do "Copy" operation for the same file for second time in order to activate "Paste" menu.

**Comment by lurch** [comment] 2024-12-29 12:40
Apparently a fix was devised in #343 , so closing this.

**Closed as completed by lurch** 2024-12-29 12:40 UTC

**Comment by ic-dev21** [comment] 2025-06-17 23:54
Any headway made with this? I have two raspi OS installs and I am unable to paste folders or files, option is always greyed out.

**Comment by lurch** [comment] 2025-06-18 08:24
@ic-dev21 Are you also using a third-party clipboard manager? If not, please create a new issue with detailed steps for how to reproduce your issue.

**Comment by qrp73** [comment] 2025-07-08 13:25
@ic-dev21, I wrote a small and simple replacement for clipman: https://github.com/qrp73/clipman2

it doesn't have much features, just allows to do copy/paste flawlessly as it should be, nothing else.
So you can compile, install and use it instead of clipman and it solves the issue.
See readme for details.
I'm using it with raspi os labwc for a long time and it works great :)
