### ISSUE TITLE
ImageViewer cannot show WEBP file which has PNG file extension

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#246] opened 2024-04-23 22:58 UTC
Steps to reproduce:
1) download any WEBP file and rename it to TEST.PNG
2) Open it with Image Viewer

Expected result: image is decoded and displayed as it happens in web browsers.

Actual result: error message shown with image decoding error.

I caught this issue in mono application which probably use the same library to decode images. 

PS: since file has PNG extension, it is possible that this may be expected behavior, I'm not sure. But since web browsers can decode PNG file with WEBP content with no issue, I think there is a sense to support it for ImageViewer and other apps which use the same library to decode images. Just try to open TEST.PNG with actual WEBP content with firefox or chromium-browser and you will see that they decode it with no issue...

Here is example of webp image with png file extension:
![kitten-and-puppy-close-up](https://github.com/raspberrypi/bookworm-feedback/assets/46676744/70ab8b34-17ca-4fae-8921-544a15908538)

**Comment by lurch** [comment] 2024-04-24 11:14
This is an upstream problem. Closing as a duplicate of https://github.com/mate-desktop/eom/issues/257

**Closed as not planned by lurch** 2024-04-24 11:14 UTC
