### ISSUE TITLE
Codec Zero audio recording doesn't work with latest raspberry pi os

### ISSUE THREAD

**Issue by impact27** [raspberrypi/bookworm-feedback#66] opened 2023-10-14 07:21 UTC
I have a raspberry pi 2 W and a IQaudIO codec zero.
I installed the latest raspberry pi os (bookworm) with the Raspberry Pi Imager and followed the instructions here:
https://www.raspberrypi.com/documentation/accessories/audio.html

The recorded audio (with arecord) with the built-in microphone are empty, as if the microphone volume is turned down to zero.

I tried it twice with bookworm and then used raspberry pi OS (Legacy) (Bullseye) with the Raspberry Pi Imager and followed the same instructions (I had to change "sudo nano /boot/firmware/config.txt" to "sudo nano /boot/config.txt") and now it works as expected

**Comment by lurch** [comment] 2023-10-14 11:20
Duplicate of #24

**Closed as not planned** 2023-10-14 11:27 UTC
