### ISSUE TITLE
Right click on Audio icon crashes taskbar  in X11/ Pulseaudio mode

### ISSUE THREAD

**Issue by KenT2** [raspberrypi/bookworm-feedback#76] opened 2023-10-15 09:57 UTC
How to reproduce:
Use sudo raspi-config to select X11 mode and Pulseaudio mode
Reboot
Right click on the audio icon on the taskbar to change audio device

Expect to see:
Menu to select audio device
 
What I see:
Task bar disappears then comes back

Query:
Do I actually need to select Pulseaudio in X11 mode? Leaving it on Pipewire seems to work OK

**Comment by qrp73** [comment] 2023-10-15 16:16
In my case it works as expected. I'm using CX31993 usb dongle as sound card.

**Comment by spl237** [comment] 2023-10-16 08:03
I can repeat. You shouldn't need to use PulseAudio with X11 though.

**Comment by spl237** [comment] 2023-10-16 08:35
Problem found - it was caused by a fix for a different problem we introduced last week! Fixed - will be in next update.

**Closed as completed by spl237** 2023-10-16 08:35 UTC

**Comment by penguin-stack** [comment] 2025-05-31 22:48
Issue has reappeared in 

Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.12.25+rpt-rpi-v8

Taskbar is disappearing when right click on audio icon

**Comment by spl237** [comment] 2025-06-01 09:31
> Issue has reappeared in
> 
> Operating System: Debian GNU/Linux 12 (bookworm) Kernel: Linux 6.12.25+rpt-rpi-v8
> 
> Taskbar is disappearing when right click on audio icon

Works fine for me on the latest image in both X and Wayland, and both PulseAudio and Pipewire. Looks like something specific to your system.

**Comment by penguin-stack** [comment] 2025-06-01 16:06
Using Wayland and Pipewire on RPi4 Model B, the issue seems to happen very occasionally

**Comment by spl237** [comment] 2025-06-01 18:11
If you can come up with a repeatable test case, I will investigate, but I can't say I have ever seen this happen on any of my images.
