### ISSUE TITLE
Purging Geany leaves residue

### ISSUE THREAD

**Issue by by** [raspberrypi/bookworm-feedback#158] opened 2023-12-05 12:36 UTC
During `apt purge geany`, the file `/usr/share/raspi-ui-overrides/applications/geany.desktop` does not get deleted, so the icon still resides in the pull-down menu.

**Comment by XECDesign** [comment] 2023-12-05 12:52
@spl237 I think some .desktop files there are missing a TryExec line.

**Comment by JinShil** [comment] 2023-12-06 00:10
Duplicate of https://github.com/RPi-Distro/raspberrypi-ui-mods/issues/47

**Comment by lurch** [comment] 2023-12-06 00:32
Thanks @JinShil , closing this as a duplicate.

**Closed as not planned by lurch** 2023-12-06 00:32 UTC
