### ISSUE TITLE
Official display 7 inch: Pi os does not rotate touch or handle double touch if wayland is active and rotated 180 degrees on bookworm

### ISSUE THREAD

**Issue by tigernero79** [raspberrypi/bookworm-feedback#140] opened 2023-11-12 14:59 UTC
after several tests with a Raspberry pi4 4gb version 1.4 and official Raspberry 7 inch display.  I noticed that the touch does not rotate if we rotate the image 180 degrees from here.  in practice the touch remains unrotated and this means that when you click on the touchscreen you see the mouse move opposite.  another serious thing is the double touch with a finger on the touchscreen which, with the image rotated using the desktop function, does not work.  unable to open any folder.  you are forced to return to the x11 environment and disable the "dtoverlay=vc4-kms-v3d" item in config.txt to have a functioning touchscreen if the display is rotated and set lcd_rotate=2 to rotate it because even in the x11 environment if rotated from the desktop setting it rotates display but not touchscreen.  Is it possible in Wayland to have 180 degree rotation working with a touchscreen that rotates together with the image?  and above all with wayland is it possible to double tap to open a folder or an application on the desktop?

**Comment by lurch** [comment] 2023-11-29 15:17
Double-touch doesn't work (yet) for a non-rotated touchscreen either, see #15 

To rotate the touchscreen, see https://www.raspberrypi.com/documentation/accessories/display.html#changing-the-screen-orientation

Closing this as a duplicate of #15

**Closed as completed by lurch** 2023-11-29 15:17 UTC
