### ISSUE TITLE
Huge memory leak

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#275] opened 2024-07-11 00:23 UTC
I'm using raspberry pi 4 with 4GB RAM and latest bookworm 64 with wayland.

I notice that after some period of runtime (it may take about 6 hours) with using different apps, there is a huge memory leak. When I close all user processes, the gnome-system-monitor shows that there is 1.2 GB RAM in usage, but on process list page I don't see processes with so large memory consumption.

btop shows 1.12 GB memory in use, but also there is no processes which consume a lot of memory.

Here is output of free (all user processes are closed):
```
$ free
               total        used        free      shared  buff/cache   available
Mem:         3862616     1137532     1615380      680648     1867836     2725084
Swap:              0           0           0

$ smem -tw
Area                           Used      Cache   Noncache 
firmware/hardware                 0          0          0 
kernel image                      0          0          0 
kernel dynamic memory       2354356    2240392     113964 
userspace memory             412004     127728     284276 
free memory                 1096256    1096256          0 
----------------------------------------------------------
                            3862616    3464376     398240 

$ sudo ipcs -m

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status      
```

For some unknown reason, htop shows memory usage 392M/3.68G:
![20240711_02h56m21s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/46676744/bea61765-edd3-400e-8419-89751ba6f466)

I tried to kill almost all processes one-by-one, but nothing helps. Used memory remains at more than 1GB.

When I reboot the system, memory usage returns to about 450 MB. 

Here is results just after system reboot:
```
$ free
               total        used        free      shared  buff/cache   available
Mem:         3862616      400640     3130404       34200      433828     3461976
Swap:              0           0           0

$ smem -tw
Area                           Used      Cache   Noncache 
firmware/hardware                 0          0          0 
kernel image                      0          0          0 
kernel dynamic memory        339000     251640      87360 
userspace memory             400208     182128     218080 
free memory                 3123408    3123408          0 
----------------------------------------------------------
                            3862616    3557176     305440 

$ sudo ipcs -m

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status      
```

![20240711_04h06m15s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/46676744/315847c8-ea71-4cbe-b092-27f8ec3a3ca7)

It looks that the memory leak is in `shared` memory, is it correct? How to check which process cause it?

Since there is no information about processes which consume so many memory, I'm confused. How to check where is memory leak?

**Comment by lurch** [comment] 2024-07-11 08:59
>  (it may take about 6 hours) with using different apps

Unless you can come up with a repeatable reproduction scenario, unfortunately I don't think there's anything we can do to investigate this.

> It looks that the memory leak is in shared memory, is it correct? How to check which process cause it?
Since there is no information about processes which consume so many memory, I'm confused. How to check where is memory leak?

I guess this is just a general Linux problem, rather than anything Raspberry Pi specific? A quick Google search finds e.g. https://github.com/0voice/kernel_memory_management/blob/main/%E2%9C%8D%20%E6%96%87%E7%AB%A0/5%20useful%20tools%20to%20detect%20memory%20leaks%20with%20examples.md

I'll close this issue for now, but feel free to follow-up if you do find a good way of reproducing this.

**Closed as not planned by lurch** 2024-07-11 08:59 UTC

**Comment by qrp73** [comment] 2024-07-11 09:06
> Unless you can come up with a repeatable reproduction scenario, unfortunately I don't think there's anything we can do to investigate this.

This is a stable repeatable reproducion scenario, just use different apps and see how shared memory usage smoothly grows up.

Is there a way to detect which process eats it?

**Comment by popcornmix** [comment] 2024-07-11 09:31
I've found [this script](https://www.zyxware.com/articles/4446/show-total-memory-usage-by-each-application-in-your-ubuntu-or-any-gnu-linux-system) useful on my ubuntu laptop.
It's standard linux so should work on a Pi.

**Comment by qrp73** [comment] 2024-07-11 09:59
> I've found [this script](https://www.zyxware.com/articles/4446/show-total-memory-usage-by-each-application-in-your-ubuntu-or-any-gnu-linux-system) useful on my ubuntu laptop. It's standard linux so should work on a Pi.

The problem here is that leaked memory is missing from process list. It is not available to use and there is no info about processes that using it. I just found that it is displayed as shared memory in ```free``` command output. There is no information available who allocated and using it. As I said before attempt to kill all running processes one-by-one don't affect shared memory usage. Something just holds more than 1 GB memory and don't release it and there is no information who is using it.

**Comment by popcornmix** [comment] 2024-07-11 10:33
If you continue to wait, do things fail catestrophically with out-of-memory errors?

**Comment by qrp73** [comment] 2024-07-12 13:32
yes, usually it leads to system freeze due to out of memory with wayfire crashing. But if you're just waiting it don't grows. It grows when you working with different apps. And I'm not sure which app is the root of cause because there is no way to see which app eats that memory. It looks like some kind of kernel memory leak.

I notice very huge memory leak grow when worked with Octave, but I'm not sure if it was Octave, because when I run it for test I don't see major memory leak.

**Comment by popcornmix** [comment] 2024-07-12 14:11
I think it's clear this isn't something that affects most users, or the forums would be swamped with reports.
So there is something specific to your use case that provokes it.

If you can provide instructions, starting with a clean RPiOS image, followed by a sequence of steps (perhaps a script that launches and quits a specific app) that results in an out of memory failure we can investigate.

**Comment by lurch** [comment] 2024-07-12 15:15
Have you checked the size of your tmpfs filesystems? https://unix.stackexchange.com/questions/307015/what-is-the-meaning-of-shared-memory-in-the-free-command

**Comment by qrp73** [comment] 2024-07-13 04:09
> Have you checked the size of your tmpfs filesystems?

Thanks, no I didn't checked this part of memory and this seems like a plausible explanation for where memory leaks. Needs more investigation to check it.

A short test shows that there is discrepancy:
```
$ free -k && grep Shmem /proc/meminfo && df -BK | grep tmpfs
               total        used        free      shared  buff/cache   available
Mem:         3862616     1817412     1306520      148232      964400     2045204
Swap:              0           0           0
Shmem:            148232 kB
tmpfs            386264K     1424K   384840K   1% /run
tmpfs           1931308K      424K  1930884K   1% /dev/shm
tmpfs              5120K       16K     5104K   1% /run/lock
tmpfs            386260K       48K   386212K   1% /run/user/1000
```
1424+424+16+48 = 1912K

while ```free -k``` and ```grep Shmem /proc/meminfo``` reports 148232K. 

Where is the rest 148232-1912=146320K of memory?

There is no such 146MB discrepancy on the example from the link that you're provided.

**Comment by ashah7** [comment] 2024-11-04 19:26
did you ever manage to get to the bottom of this
I'm seeing similar issues on the Raspberry pi using bookworm

**Comment by popcornmix** [comment] 2024-11-05 12:51
Commenting "me too" on a closed issue (when the issue is unlikely to be the same root cause) is unlikely to be useful.

If you have a reproducible memory leak, then explain exactly how to provoke it. e.g.
Install RPiOS 64-bit image on a an sdcard
Boot on Pi4 with a 4kp60 display.
Install package X with apt.
Launch X, close X and repeat.
Each launch sees "available" column from `free -h` increase by 10M, until it approaches zero and desktop gui is restarted.

and report this is a new issue. Without detailed instructions of what you are doing, there is nothing to investigate.
