### ISSUE TITLE
Functionality to Activate, Hide Application Windows in Bookworm release

### ISSUE THREAD

**Issue by AbhijithBn** [raspberrypi/bookworm-feedback#244] opened 2024-04-12 10:29 UTC
Thank you for all your efforts into the Bookworm release.

**Use case**:
Launch applications and then be able to Hide(Move to Back) and Activate(Move to Front) these windows NOT via the attached keyboard but programmatically. The application we are trying to work with is Chromium browser

**What we tried**

In the Bullseye release of Raspberry Pi with X Displaying system, we were able to activate, hide application windows programmatically using the [xdotool](https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html) program. Here are a few example of the commands
```
xdotool windowactivate
xdotool windowminimize
```

Currently the Raspberry Bookworm release, we are not able to activate, hide application windows programmatically.

We tried modifying the ~/.config/wayfire.ini file  [Rules] directive to maximize and minimize windows , but that does not seem to work.

We tried the ipc-rules plugin as per the [example](https://github.com/WayfireWM/wayfire/blob/master/ipc-scripts/ipc-rules-demo.py) but this plugin is only available in wayfire version 0.8.0 as per this [article](https://wayfire.org/2023/10/07/Wayfire-0-8.html) and the current wayfire in Raspberry Pi is 0.7.5.

Please let us know if there are any other things that we can try to solve this problem or if there are other things we might be missing.

**Comment by lurch** [comment] 2024-04-12 11:47
I did a bit of searching, and I wonder if one of these might be a useful research-starting-point for what you're trying to do?
https://www.reddit.com/r/gnome/comments/111gjv4/there_is_really_no_way_to_programmatically/
https://www.reddit.com/r/linuxquestions/comments/u5mxzi/xdotool_alternative_for_wayland/

As this is a question about using Wayfire, and not a bug-report against Raspberry Pi OS Bookworm, I'm going to close this and suggest you try asking for further help at https://forums.raspberrypi.com/

**Closed as not planned** 2024-04-12 11:47 UTC
